export const candidatesApi = [
    {
        index: 0,
        name: "John Doe",
        email: "john.doe@examp.com",
        score: 85,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL_Q_srm4IRf3KADpkpoNQlbuLmqlXh5kl3CEjPU9WGg&s",
        about: "I am a highly motivated individual with a passion for problem-solving and a keen eye for .",
        experience: "With 3 years of experience in software development, I have worked on various proj.",
        hobbies: "In my free time, I enjoy reading books on technology and self-improvement. ",
        introduction: "Hello, I'm John Doe. I'm a software developer with a passion for creating elegant solutionsout the opportunity.",
        videos: [
            "https://www.youtube.com/embed/SxoRrlfkHho",
        ],
        status: "shortlisted",
        communication:8,
        handling:7,
        behaviour:9
    },
    {
        index: 1,
        name: "Jane Smith",
        email: "jane.smith@examp.com",
        score: 32,
        image: "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters/large/800/Jane-Smith.Mr-and-Mrs-Smith.webp",
        about: "I am a dedicated professional with a strong background in marketing and a proven ",
        experience: "With 5 years of experience in marketing, I have managed multiple projects and tise in digital.",
        hobbies: "Outside of work, I enjoy traveling to new destinations, experimenting with new ",
        introduction: "Hi, I'm Jane Smith. As a marketing specialist, I am passionate about creating ",
        videos: [
        ],
        status: "review",
        communication:7,
        handling:9,
        behaviour:8
    },
    {
        index: 2,
        name: "Alex Johnson",
        email: "alex@examp.com",
        score: 78,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCBpuZyuAHOAJ9CWJsO91FUQ338CBbfGrSZWqzPVvDoQ&s",
        about: "I am passionate about coding and enjoy building scalable solutions that make a dif",
        experience: "Having spent 2 years in web development, I have gained valuable experience in.",
        hobbies: "In my spare time, I love playing video games, watching movies, and playing soccer.",
        introduction: "Hey there, I'm Alex Johnson. I'm a web developer with a passion for creating.",
        videos: [
        ],
        status: "shortlisted",
        communication:8,
        handling:6,
        behaviour:7
    },
    {
        index: 3,
        name: "Emily Brown",
        email: "emily@example.com",
        score: 50,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcHFCSR355keLNi7Dy0TTE1ePujHpnGGCXOuuv1dJ4yw&s",
        about: "I am an enthusiastic learner who thrives in creative environments. With a background .",
        experience: "With 4 years of experience in graphic design, I have worked on a wide range of p.",
        hobbies: "Outside of work, I enjoy painting landscapes, traveling to new art destinations, a.",
        introduction: "Nice to meet you, I'm Emily Brown. I'm a graphic designer with a passion for.",
        videos: [
        ],
        status: "review",
        communication:2,
        handling:6,
        behaviour:5
    },
    {
        index: 4,
        name: "Michael Davis",
        email: "michael@example.com",
        score: 88,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF0lHNzytnb_Z6eMupNX9TQsGTODVRVC8tz65viDWMWA&s",
        about: "I am a detail-oriented professional with a passion for finance and analytics. With",
        experience: "In my finance career, I have worked in various roles, including financial analysis",
        hobbies: "Outside of work, I enjoy reading financial journals, running marathons, and experimenting I help ",
        introduction: "Hi, I'm Michael Davis. I'm a finance professional with a passion for numbers and a drio ",
        videos: [
        ],
        status: "shortlisted",
        communication:9,
        handling:7,
        behaviour:8
    },
    {
        index: 5,
        name: "Emma Wilson",
        email: "emma@example.com",
        score: 42,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtJcfgOAc8USRCIZQS-Bo-5eldLn6s5x8h8nY6oQuaeB6KL2hbTC-bSgNd0TTvIJaN-nY&usqp=CAU",
        about: "I am an energetic and creative person who loves taking on new challenges. With a background in mark",
        experience: "With 3 years of experience in marketing, I have worked on various projects, including social media c m.",
        hobbies: "Outside of work, I enjoy photography, traveling to new destinations, and hiking in nature. I also enjoyind.",
        introduction: "Hello, I'm Emma Wilson. I'm a marketing professional with a passion for creating impactfulring my creativ.",
        videos: [
        ],
        status: "review",
        communication:7,
        handling:5,
        behaviour:6
    },
    {
        index: 6,
        name: "Daniel Lee",
        email: "daniel@example.com",
        score: 95,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_1rIZlEH0a5_3L2ICq_VSrliy-UKq3FBaxBc4Fnc37dblTfE4KlIuFqsfB2nNsrL-y-0&usqp=CAU",
        about: "I am a dedicated software engineer with a passion for building scalable and reliable systems. With 7 yearpment .",
        experience: "Throughout my career, I have worked on a variety of projects, including e-commerce platforms, SaaS a",
        hobbies: "In my spare time, I enjoy gaming, coding side projects, and reading tech blogs. I am also a mentor at a .",
        introduction: "Nice to meet you, I'm Daniel Lee. I'm a software engineer with a passion for building innovative solution.",
        videos: [
        ],
        status: "shortlisted",
        communication:8,
        handling:9,
        behaviour:7
    },
    {
        index: 7,
        name: "Olivia Martinez",
        email: "olivia@example.com",
        score: 36,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwrEr4k3EmXltEFVGtd4yLDomBpMu6xGR_IsJJzDBJy7vrE0CqkDhXpIo1usgaxJKBOcA&usqp=CAU",
        about: "I am a creative thinker with a passion for design and innovation. With 4 years of experience in graphic design,",
        experience: "In my graphic design career, I have collaborated with clients to bring their visions to life through ce Ado.",
        hobbies: "Outside of work, I enjoy drawing, practicing yoga, and experimenting with new art techniques. I am alsochildren in .",
        introduction: "Hello, I'm Olivia Martinez. I'm a graphic designer with a passion for creating visually stunning dativit.",
        videos: [
        ],
        status: "review",
        communication:6,
        handling:5,
        behaviour:4
    },
    {
        index: 8,
        name: "William Clark",
        email: "william@example.com",
        score: 30,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtzSFup4GceRsWQiRrWaTc9yqYkBzWvfyzgoUREXNM4-heoYx43nY_L2YIcxlhqNeInqw&usqp=CAU",
        about: "I am a team player with strong communication skills and a passion for project management. With 5 years of ex .",
        experience: "Throughout my career, I have managed a wide range of projects, including product launches, marketing cals.",
        hobbies: "Outside of work, I enjoy traveling with my family, attending live music events, and playing soccer with here.",
        introduction: "Hi, I'm William Clark. I'm a project manager with a passion for leading teams and delivering results.o.",
        videos: [
        ],
        status: "review",
        communication:5,
        handling:6,
        behaviour:3
    },
    {
        index: 9,
        name: "Sophia Rodriguez",
        email: "sophia@example.com",
        score: 79,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtzSFup4GceRsWQiRrWaTc9yqYkBzWvfyzgoUREXNM4-heoYx43nY_L2YIcxlhqNeInqw&usqp=CAU",
        about: "I am a results-driven professional with a focus on efficiency and effectiveness. With 6 years of experience.",
        experience: "In my sales career, I have worked in various industries, including technology, healthcare, and retail. ",
        hobbies: "Outside of work, I enjoy hiking in the mountains, cooking new recipes, and painting landscapes. .",
        introduction: "Nice to meet you, I'm Sophia Rodriguez. I'm a sales professional with a proven track recor.",
        videos: [
        ],
        status: "shortlisted",
        communication:7,
        handling:2,
        behaviour:8,
    }
];
